### ISSUE TITLE
Data Import

### ISSUE THREAD

**Issue by MNTsnowman** [Vitek-Lab/MSstatsPTM#22]
Hi

I have finally processed my dataset with MSstats, and now i would like to have a closer look at the PTMs with MSstatsPTM. However, I'm stuck at importing the data. The data i have is the MSstats datafile from FragPipe, however, this does not apper to be correct. when I execute the dataSummaraizationPTM(raw, verbose = TRUE) it produces the following error : Error in .summarizeCheck(data, "LF") : PTM peak list is missing. Input data must be of type list with an element named "PTM" - stop. So i guess this format is incorrect (?), but i cannot find any examples of the correct format either.

Therefore, would it be possible to get an example of the input csv needed for MSstatsPTM? And would it be possible to make the output from FragPipe work (?) maybe by combining it with the used fasta file, or generated pepxml file(s)?

I hope you can help.

**Comment by devonjkohler** [comment]
Hi,

There are actually example data files in the package for both Label Free and TMT data. You can access them using the code below.

```
library(MSstatsPTM)

## TMT
head(raw.input.tmt$PTM)
head(raw.input.tmt$PROTEIN)

## LF
head(raw.input$PTM)
head(raw.input$PROTEIN)
```

I would suggest taking a look at the vignettes in the package because they go over some of the specific formatting needs.

Would you be able to share any small example data from FragPipe? I would be happy to build in a converter for it but currently do not have any example output!

Best,
Devon

**Comment by MNTsnowman** [comment]
Hi Devon

Thanks a lot for the reply, and thanks a lot for providing those examples.

I'm still not entirely sure if the structure requiered for the input *.csv file. My guess is that the requiered columns are : ProteinName PeptideSequence Condition BioReplicate Run   Intensity PrecursorCharge

If so, i don't understand why it isn't compatible with the data I have. The MSstats format generated by FragPipe has the following colums : ProteinName	PeptideSequence	PrecursorCharge	FragmentIon	ProductCharge	IsotopeLabelType	Condition	BioReplicate	Run	Intensity

You can read mroe about the MSstats format generated by Fragpipe here : https://fragpipe.nesvilab.org/docs/tutorial_msstats.html

The only visible difference I can spot, is that in your exampel data the PTMs are annotated using a "*" in the peptide sequence, while they do [xx.xxx]. But to differentiate between PTMs wouldn't it be better to use the [xx.xxx] format? I mean, in cases where O-linked glycans are analyzed, the positions are probably the same but the exact PTM is not.?

Kind Regards
Martin

**Comment by devonjkohler** [comment]
Hi Martin,

The format of the peptide sequence shouldn't be a problem. One potential problem is that the ProteinName column needs to include both the protein and the modification site. So in the example data you'll see that column includes names like "Q9UHD8_K262". If that is not the case you can either identify the mod sites and add them in, or simply paste the ProteinName and PeptideSequence columns together - `df$ProteinName <- paste(df$ProteinName, df$PeptideSequence, sep = "_")`

Hope this helps!
Devon

**Comment by MNTsnowman** [comment]
Hi Devon

Sorry for the late reply, validating the steps previous to this apparently takes longer than i though (...). Anyhow, if that's the only difference, i think i can extract the information and merge it using some of the other files generated by FragPipe. One question though, i have some peptides that contains multiply PTMs, I would like to keep all of these in the same entry, would that be possible? My guess would be that the name should then be "Q9UHD8_K262_S264". Would this work? If yes, I can generate the input, i think. :)

Also, sorry for all the basic R questions, i was introduced to R almost 3 weeks ago by now, so getting it to work probberly is still, ehh, challenging. Therefore, I also have to admit that I'm not quite sure of how to import the data from my csv file into R in a setup/layot that MSstatsPTM will understand. I see the point of the vignettes, but that's on an example dataset that's build into the MSstatsPTM package, thus i cannot see the structure of the dataset and how it compares to the one i have. For the exercise, lets ashume that the format is the MSstat format generated by Fragpipe with the addition of PTM positions (ashuming that multiply PTMs per peptide is supported). What commands should be executed to do this?

Kind Regards
Martin

**Comment by MNTsnowman** [comment]
Hi Devon

I found a bug in the vignettes for the LabelFree workflow from 2021-10-07. I try to read in the data and to convert it (?)

  annotation <- data.frame('Condition' = c('Control', 'Control', 'Control',
                                         'Treatment', 'Treatment', 'Treatment'),
                         'BioReplicate' = c(1,2,3,4,5,6),
                         'Run' = c('prot_run_1', 'prot_run_2', 'prot_run_3',
                                   'phos_run_1', 'phos_run_2', 'phos_run_3'),
                         'Type' = c("Protein", "Protein", "Protein", "PTM", 
                                    "PTM", "PTM"))

  raw.input <- ProgenesistoMSstatsPTMFormat(raw_ptm_df, annotation, 
                                            raw_protein_df, fasta_path)

The conversion fails and reports this error : "Error in as.data.table(ptm_input) : object 'raw_ptm_df' not found"

I got no clue what's going on, but it makes it deficult to follow the rest of the example.

Kind Regards
Martin

**Comment by devonjkohler** [comment]
Hi Martin @MNTsnowman,

Sorry for the delay in response. For your first question, you are exactly correct about the format for the two (or more) modification sites. "Q9UHD8_K262_S264" is how it should be formatted. 

In terms of the vignette, I apologize for the bug. We do not have publicly available, label free modified data, but I still wanted to include an example of how you could use the base MSstats functions for conversion. That specific piece will not run and is just an example. I'll definitely add a note there that the code is merely an example and does not actually run. 

If you are still having problems, I'd be happy to help write some code for your specific situation.

Devon

**Comment by MNTsnowman** [comment]
Hi Devon @devonjkohler 

I have not been able to proceed with this since, I was planning on getting back on it when i have a bit more time, like next week maybe. 

I would love to get some assistance with the coding, maybe we could do it via e-mail though?

Martin

**Comment by devonjkohler** [comment]
Hi Martin @MNTsnowman,

I'd be happy to help over email. We are actually working on a PTM converter for FragPipe now so I think it might be very helpful for both of us! 

Feel free to shoot me an email at kohler.d@northeastern.edu.

Best,
Devon
