### ISSUE TITLE
PStoMSstatsPTMFormat PTM site annotation bug

### ISSUE THREAD

**Issue by Gd-Hao** [Vitek-Lab/MSstatsPTM#35]
Hi! @devonjkohler 
I found a little bug in `PStoMSstatsPTMFormat` function. When peptide sequence detected start at the first amino acid of protein, sometime it will lost M at it's N terminal. PEAKS notes the sequence as M.XXXXX(notice the dot after M)  and "start" as 2. But the completed peptide  are noted as MXXXXX and "start" as 1. It results site annotation mistake.
Here are sample file
[Q9ZV07.csv](https://github.com/Vitek-Lab/MSstatsPTM/files/9797698/Q9ZV07.csv)
```
library(MSstats)
library(MSstatsPTM)
library(MSstatsConvert)
library(tidyverse)
library(data.table)

annotation = data.table("Raw.File" = c('WTFL_1', 'WTFL_2', 'WTFL_3',
                                       'WTFD_1', 'WTFD_2', 'WTFD_3',
                                       'CQFD_1', 'CQFD_2', 'CQFD_3'),
                        "BioReplicate" = c('WTFL_1', 'WTFL_2', 'WTFL_3', 
                                           'WTFD_1', 'WTFD_2', 'WTFD_3',
                                           'CQFD_1', 'CQFD_2', 'CQFD_3'),
                        "Condition" = c('WTFL', 'WTFL', 'WTFL', 'WTFD',
                                        'WTFD', 'WTFD', 'CQFD', 'CQFD', 'CQFD'),
                        "Run" = c(1, 2, 3, 4, 5, 6, 7, 8, 9))

sample_PIP26 <- read_csv('Q9ZV07.csv')
msstats_PIP26 = PStoMSstatsPTMFormat(sample_PIP26, annotation,
                                      use_unmod_peptides = TRUE,
                                      target_modification = "Phosphorylation",
                                      remove_oxidation_peptides = TRUE,
                                      remove_multi_mod_types = TRUE)
```

Q9ZV07_T6_S10 actually is Q9ZV07_T7_S11.

**Comment by devonjkohler** [comment]
Hi @Gd-Hao,

Thanks for letting me know about this bug. I just pushed a fix to the function in the [feature-peaks_converter ](https://github.com/Vitek-Lab/MSstatsPTM/tree/feature-peaks_converter) branch. Let me know if you still see the error.

Devon

**Comment by Gd-Hao** [comment]
Hi @devonjkohler ,

Thank you very much for helping. Everything went well! 

Guodong
