### ISSUE TITLE
DIANN phospho to MSstatsPTM?

### ISSUE THREAD

**Issue by tnguyenwi** [Vitek-Lab/MSstatsPTM#36]
Hello,
Can you please help me to convert the result of phosphoproteomics from DIA-NN to the long format for MSstatsPTM?
Thanks

**Comment by devonjkohler** [comment]
Hi @tnguyenwi,

I would be happy to add a converter for DIA-NN. Do you have any example data I could use to build it? We currently do not have a DIA-NN converter because we do not have access to any datasets processed with the tool.

Devon

**Comment by tnguyenwi** [comment]
Thanks, Devon,
Sure, can you please let me know how I can send you the dataset privately?
Thanks,
Thao

**Comment by cutleraging** [comment]
Hello,

I am wondering if this converter was created. I have some data that I could share.

Thanks,
Ronnie

**Comment by devonjkohler** [comment]
Hi @cutleraging,

The converter has not been created yet. We are currently working on adding a bunch of converters for the next Bioc release. Could you email me at kohler.d@northeastern.edu? I can definitely build the converter with your data.

Devon

**Comment by devonjkohler** [comment]
This is now live on Github. Will be pushed to Bioc on 10/25/2023
