### ISSUE TITLE
Many NAs in my PTM model

### ISSUE THREAD

**Issue by jjGG** [Vitek-Lab/MSstatsPTM#42]
Dear MSstatsPTM developer, 

I am trying to analyse my Phospho-proteomics data (combined with the protein-data for the same conditions). 
I am working with **MSstatsPTM v. 1.4.2**. (since I have R 4.1.1)

My experimental design:
- DIA data analysed with Spectronaut (MSstats-export schema)
- 12 conditions in total -> here we will focus on 9 comparisons (contrasts)
- PTM data contains fractionated data
- Protein data (not fractionated)
- "only" 2 biological replicates

My issues:
- I successfully can run the "dataSummarizationPTM" function
- I can produce the "dataProcessPlotsPTM QCPLOT"
- I get an error when trying the "Profileplot" for a single protein: 

`Error in if (unique(datafeature$LABEL) == "L") { : 
  argument is of length zero
In addition: Warning messages:
1: In as.data.table.list(x, keep.rownames = keep.rownames, check.names = check.names,  :
  Item 1 has 0 rows but longest item has 1; filled with NA
2: In as.data.table.list(x, keep.rownames = keep.rownames, check.names = check.names,  :
  Item 3 has 0 rows but longest item has 1; filled with NA
3: In as.data.table.list(x, keep.rownames = keep.rownames, check.names = check.names,  :
  Item 4 has 0 rows but longest item has 1; filled with NA`

Furthermore:
- I can successfully run the "groupComparisonPTM" function
--> BUT: I do have only very few non NAs in my PTM.model 
(see head)

```
> head(MSstatsPTM.model$PROTEIN.Model)
      Protein           Label     log2FC        SE     Tvalue DF       pvalue   adj.pvalue issue MissingPercentage ImputationPercentage
1: A0A024RBG1 MitMCF7-MitHela  1.1242456 0.2569988  4.3745162 11 1.109177e-03 0.0042231180  <NA>         0.1166667            0.1166667
2: A0A024RBG1  MitMDA-MitHela -0.2200633 0.2569988 -0.8562814 11 4.101078e-01 0.5134375575  <NA>         0.2166667            0.2166667
3: A0A024RBG1 MitCAKI-MitHela -1.6858584 0.2569988 -6.5597902 11 4.080725e-05 0.0002363774  <NA>         0.3166667            0.3166667
4: A0A024RBG1 CytMCF7-CytHela  1.2933641 0.2569988  5.0325681 11 3.824068e-04 0.0018616307  <NA>         0.2000000            0.2000000
5: A0A024RBG1  CytMDA-CytHela -0.1510224 0.2569988 -0.5876386 11 5.686417e-01 0.6639213900  <NA>         0.3166667            0.3166667
6: A0A024RBG1 CytCAKI-CytHela -1.5773173 0.2569988 -6.1374491 11 7.336670e-05 0.0003472445  <NA>         0.3833333            0.3833333
> head(MSstatsPTM.model$ADJUSTED.Model)
              Protein           Label    log2FC        SE    Tvalue       DF     pvalue adj.pvalue GlobalProtein
1:        O00571_S594 MitMCF7-MitHela 0.2390738 1.3005360 0.1838271 3.066241 0.86563639 0.90801020        O00571
2: O14686_C1909,T1911 MitMCF7-MitHela 6.1366935 1.3560460 4.5254316 1.656271 0.06382007 0.13868707        O14686
3:       O14686_T4505 MitMCF7-MitHela 2.4378909 0.8083912 3.0157316 5.669121 0.02524163 0.07143857        O14686
4:         O15173_S90 MitMCF7-MitHela 4.6534889 0.9402860 4.9490143 3.363847 0.01201697 0.04291776        O15173
5:          O15258_S6 MitMCF7-MitHela 1.0598729 0.7029284 1.5077963 3.149972 0.22449903 0.30337706        O15258
6:        O15504_S106 MitMCF7-MitHela 7.7688964 1.2385904 6.2723693 2.525961 0.01336728 0.04663004        O15504
> head(MSstatsPTM.model$PTM.Model)
                       Protein           Label log2FC SE Tvalue DF pvalue adj.pvalue               issue MissingPercentage ImputationPercentage
1: A0A0B4J2F2;P57059_S575;S575 MitMCF7-MitHela    Inf NA     NA NA     NA          0 oneConditionMissing                NA                   NA
2: A0A0B4J2F2;P57059_S575;S575  MitMDA-MitHela     NA NA     NA NA     NA         NA     completeMissing                NA                   NA
3: A0A0B4J2F2;P57059_S575;S575 MitCAKI-MitHela     NA NA     NA NA     NA         NA     completeMissing                NA                   NA
4: A0A0B4J2F2;P57059_S575;S575 CytMCF7-CytHela     NA NA     NA NA     NA         NA     completeMissing                NA                   NA
5: A0A0B4J2F2;P57059_S575;S575  CytMDA-CytHela     NA NA     NA NA     NA         NA     completeMissing                NA                   NA
6: A0A0B4J2F2;P57059_S575;S575 CytCAKI-CytHela     NA NA     NA NA     NA         NA     completeMissing                NA                   NA
```

This makes me wondering if I can trust the ADJUSTED model. 
-> is the problem, that I do have not enough replicates? (only two?) why would then the protein model still work?

best regards and thanks for looking into it.

Jonas

============ MSstats log for summariziation: ====================
`INFO  [2023-01-18 17:07:05] MSstats - dataProcess function
INFO  [2023-01-18 17:07:05] Summary method: TMP
INFO  [2023-01-18 17:07:05] censoredInt: NA
INFO  [2023-01-18 17:07:58] ** Features with one or two measurements across runs are removed.
INFO  [2023-01-18 17:08:04] ** Fractionation handled.
INFO  [2023-01-18 17:08:29] ** Updated quantification data to make balanced design. Missing values are marked by NA
INFO  [2023-01-18 17:08:29] 

INFO  [2023-01-18 17:08:38] ** There are 54194 intensities which are zero or less than 1. These intensities are replaced with 1
INFO  [2023-01-18 17:08:38] Logarithm transformation with base 2 is done
INFO  [2023-01-18 17:08:46] Factorize in columns(GROUP, SUBJECT, GROUP_ORIGINAL, SUBJECT_ORIGINAL, FEATURE, RUN)
Normalization based on median: OK [2023-01-18 17:08:48] 
INFO  [2023-01-18 17:08:51] ** Use all features that the dataset originally has.
INFO  [2023-01-18 17:09:00] 
 # proteins: 7840
 # peptides per protein: 1-899
 # features per peptide: 1-1
INFO  [2023-01-18 17:09:00] Some proteins have only one feature: 
 A4D1U4,
 A6NCC3;F8WBI6;H3BV12;I6L899,
 A6NDR6;O00470;O14770;Q99687,
 A6NHN6,
 A6NK44 ...
INFO  [2023-01-18 17:09:01] 
                    Caki_cyt Caki_inter Caki_mit Hela_cyt Hela_inter Hela_mit MCF7_cyt MCF7_inter MCF7_mit MDA_cyt MDA_inter MDA_mit
             # runs        2          2        2        2          2        2        2          2        2       2         2       2
    # bioreplicates        2          2        2        2          2        2        2          2        2       2         2       2
 # tech. replicates        1          1        1        1          1        1        1          1        1       1         1       1
INFO  [2023-01-18 17:09:06] Some features are completely missing in at least one condition:  
 _EVYEEAGVKGK__2_NA_NA,
 _EVYEEAGVKGK__3_NA_NA,
 _LLGIFEQNQDR__2_NA_NA,
 _LLGIFEQNQDRK__2_NA_NA,
 _LLGIFEQNQDRK__3_NA_NA ...
INFO  [2023-01-18 17:09:06] == Start the summarization per subplot...
INFO  [2023-01-18 17:36:52] == Summarization is done.
INFO  [2023-01-18 17:37:11] Summarization complete. Returning output
`

**Comment by devonjkohler** [comment]
Hi @jjGG, 

I know this is an older issue, but I wanted to respond in case you or anyone else runs into this issue in the future. In terms of the NAs in the model, this is actually not a bug in the package. The NAs you listed come from non-unique proteins (e.g., you can see there are two listed separated with ";"). These are a real challenge for MSstatsPTM to deal with because we need to see the PTM and the corresponding global protein in order to perform adjustment. There was no match for these non-unique peptides in the global protein dataset (which makes sense because it would have to be the same non-unique peptides which are unlikely to be there).

I would recommend removing all non-unique peptides. There might still be a couple NAs from PTMs without a protein, but we note this now in the output. 

Hope this helps.

Devon
