### ISSUE TITLE
MSstatsPTM output

### ISSUE THREAD

**Issue by direnardak** [Vitek-Lab/MSstatsPTM#73]
Hello,
I am trying to run MSstatsPTM with my DDA phosphoproteomics data. I've seen the related ticket #45 .I've used FragPipe v20.0 and I have the MSstats.csv output. My MSstatsPTM version is v2.5.1. I checked the source code to use FragPipetoMSstatsPTMFormat function and I checked the parameters according to the info in that script. However, I am still getting errors trying to use MSstatsPTM. Can you give more information about the settings? Am I using the correct version or output from FragPipe? I also had to change column titles in experiment.annotation file. Is there any documentation about how to use FragPipe label-free output in MSstatsPTM?

**Comment by devonjkohler** [comment]
Hi @direnardak 

Is this a label free experiment? PTM information was just added to the label free MSstats.csv output from FragPipe and I am guessing it has not made it into the release version yet. You can confirm this by looking at the MSstats.csv file and seeing if PTM info is included.

If this is TMT then we will need to take a closer look at this error.

Devon

**Comment by direnardak** [comment]
Yes, it is a label free experiment. And MSstats.csv output doesn't seem to have PTM information. Since I was using the GUI version, I was using FragPipe v20.0 which was released in May. I guess I can wait for an update or try the development version. Thanks!
