### ISSUE TITLE
FragPipetoMSstatsPTMFormat - LFQ

### ISSUE THREAD

**Issue by kaupuks** [Vitek-Lab/MSstatsPTM#74]
Hello,

What files should be submitted to import LFQ data (Phospho) from fragpipe?

msstats_data = FragPipetoMSstatsPTMFormat("MSstats.csv",
                                          "experiment_annotation.tsv",
                                          mod_id_col = "STY", 
                                          localization_cutoff=.75, label_type="LF", 
                                          remove_unlocalized_peptides=TRUE)

FASTA file not provided and `Start` column missing from data. 
           MSstatsPTMSiteLocator requires one of these to be provided to 
           identify modification site number

Best Regards,
Algirdas

**Comment by devonjkohler** [comment]
Hi Algirdas,

I think your problem is that you are passing strings to the function and not the loaded data.frames. Try to load this data into R and pass that object to the function.

One note, FragPipe should automatically add your annotation information directly into the msstats.csv file so you should not need to use an annotation file.

Example code below.

Best,
Devon

```
input_data = read.csv("msstats.csv")
annotation = read.csv("experiment_annotation.tsv", sep="\t")

msstats_data = FragPipetoMSstatsPTMFormat(input_data,
annotation,
mod_id_col = "STY",
localization_cutoff=.75, label_type="LF",
remove_unlocalized_peptides=TRUE)
```

**Comment by kaupuks** [comment]
Hello,

Thanks for answer, but error is the same. Is it ok with mstats.csv ?

> head(input_data)
                ProteinName                        PeptideSequence PrecursorCharge FragmentIon
1 sp|A0A1B0GTU1|ZC11B_HUMAN RLS[79.9663]SAST[79.9663]GKPPLSVEDDFEK               3          NA
2 sp|A0A1B0GTU1|ZC11B_HUMAN RLS[79.9663]SAST[79.9663]GKPPLSVEDDFEK               3          NA
3 sp|A0A1B0GTU1|ZC11B_HUMAN RLS[79.9663]SAST[79.9663]GKPPLSVEDDFEK               3          NA
4 sp|A0A1B0GTU1|ZC11B_HUMAN RLS[79.9663]SAST[79.9663]GKPPLSVEDDFEK               3          NA
5 sp|A0A1B0GTU1|ZC11B_HUMAN RLS[79.9663]SAST[79.9663]GKPPLSVEDDFEK               3          NA
6 sp|A0A1B0GTU1|ZC11B_HUMAN RLS[79.9663]SAST[79.9663]GKPPLSVEDDFEK               3          NA
  ProductCharge IsotopeLabelType Condition BioReplicate    Run Intensity
1            NA                L     pancr            1 P175_1        NA
2            NA                L     pancr            1 P175_2        NA
3            NA                L     pancr            2 P280_1  732186.1
4            NA                L     pancr            2 P280_2        NA
5            NA                L     pancr            3 P286_1        NA
6            NA                L     pancr            3 P286_2        NA

Best,
Algirdas

**Comment by devonjkohler** [comment]
Hi Algirdas,

Apologies I should foreseen this problem. FragPipe just added PTM info to the label free msstats output a month or so ago and it has not made it into the release version yet (see https://github.com/Vitek-Lab/MSstatsPTM/issues/73 for the same discussion). You will need to check with the developers of FragPipe for the correct version, you may have to download the development version of the platform for this but I am not positive.

This will be resolved in the next release of FragPipe going forward.

**Comment by kaupuks** [comment]
It's clear now, thanks!
