### ISSUE TITLE
Input data

### ISSUE THREAD

**Issue by Giu-F** [Vitek-Lab/MSstatsPTM#78]
Hi, 
I have acquired proteome and phospho-enriched runs from the same original samples. 
To get the right input for MS stat PTM, shall I do only one search for all the files?
In other words, shall I add pSTY as variable modification for the proteome runs as well?
Thanks in advance

**Comment by tonywu1999** [comment]
Hi,

Apologies for the delay in response.  You can do separate searches for the proteome and phospho-enriched runs.  

For future questions, please post them on the MSstats google groups forum https://groups.google.com/g/msstats.  We will answer more promptly to questions posted there.

Tony
